spring:
  datasource:
    url: jdbc:postgresql://localhost:5477/bookdb
    driver-class-name: org.postgresql.Driver
    username: bookuser
    password: bookpass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changeLog-master.yaml
jackson:
  serialization:
    indent-output: true
server:
  port: 2133